#!/usr/bin/env bash
# Slow path: at least one set of patches failed sanity check → open a PR with
# `needs-review` for human triage. Don't auto-merge.

set -euo pipefail

# Branch name needs something unique; prefer web-ui SHA if present, else agent
# version, else timestamp.
SLUG="${WEBUI_NEW_SHA:-}"
[ -z "$SLUG" ] && SLUG="agent-${AGENT_NEW_VER:-unknown}"
[ -z "$SLUG" ] && SLUG="ts-$(date +%s)"
BRANCH="auto-sync/${SLUG}"

git config user.name "hermes-desktop-bot"
git config user.email "hermes-desktop-bot@users.noreply.github.com"
git checkout -b "$BRANCH"
git add -A

SUBJECT_PARTS=()
BODY_LINES=()
if [ "${WEBUI_CHANGED:-false}" = "true" ]; then
  SUBJECT_PARTS+=("hermes-web-ui ${WEBUI_TAG:-?}")
  BODY_LINES+=("- web-ui: \`v${WEBUI_OLD_VER:-?}\` → \`v${WEBUI_NEW_VER:-?}\` (${WEBUI_COMMIT_COUNT:-?} commits, [compare](https://github.com/EKKOLearnAI/hermes-web-ui/compare/${WEBUI_OLD_SHA}...${WEBUI_NEW_SHA})) — patches OK: **${WEBUI_PATCH_OK:-n/a}**")
fi
if [ "${AGENT_CHANGED:-false}" = "true" ]; then
  SUBJECT_PARTS+=("hermes-agent v${AGENT_NEW_VER}")
  BODY_LINES+=("- hermes-agent (PyPI): \`v${AGENT_OLD_VER:-?}\` → \`v${AGENT_NEW_VER:-?}\` — patches OK: **${AGENT_PATCH_OK:-n/a}**")
fi

JOINED=$(printf "%s + " "${SUBJECT_PARTS[@]}")
JOINED=${JOINED% + }

cat > /tmp/commit-msg.txt <<EOF
chore(deps): bump ${JOINED}

Bump upstream deps + desktop version (${OLD_VER} → ${NEW_VER}).

Patches sanity-check (overall): ${PATCHES_OK:-unknown}
EOF
git commit -F /tmp/commit-msg.txt
git push origin "$BRANCH"

cat > /tmp/pr-body.md <<EOF
Auto-generated by \`.github/workflows/sync-upstream.yml\`.

$(printf "%s\n" "${BODY_LINES[@]}")
- desktop package.json: \`${OLD_VER}\` → \`${NEW_VER}\`
- Patch sanity check (overall): **${PATCHES_OK:-unknown}**

### Auto-merge policy

- 🟢 If all patch sanity checks passed AND CI is green → \`gh pr merge --auto --squash\` will merge once CI completes.
- 🟡 If any patch sanity check failed → label \`needs-review\` is added; auto-merge disabled.
- 🔴 If CI fails → PR sits open, GitHub emails the owner.
EOF

PR_URL=$(gh pr create \
  --repo "$GITHUB_REPOSITORY" \
  --base main \
  --head "$BRANCH" \
  --title "chore(deps): bump ${JOINED}" \
  --body-file /tmp/pr-body.md \
  --label "auto-sync")
PR_NUM=$(echo "$PR_URL" | sed -E 's@.*/pull/([0-9]+).*@\1@')
echo "Opened PR #$PR_NUM ($PR_URL)"

if [ "${PATCHES_OK:-}" = "true" ]; then
  gh pr merge --auto --squash "$PR_NUM" --repo "$GITHUB_REPOSITORY"
  echo "✓ Auto-merge enabled (waits for CI)"
else
  gh pr edit "$PR_NUM" --repo "$GITHUB_REPOSITORY" --add-label "needs-review"
  echo "⚠ Patches lost anchors — labeled needs-review, auto-merge skipped"
fi
